replicaCount: ${replica_count}

fullnameOverride: ${fullnameOverride}
namespace: ${namespace}

# kick 3

# containerSpecOptions:
#   securityContext:
#     runAsUser: 1000
#     runAsGroup: 1000

deployment:
  containers:
  - name: ${fullnameOverride}
    image:
      repository: ${docker_repository}
      tag: ${docker_tag}
      pullPolicy: Always
    args:
    - run
    env:
      base:
        - name: TXINDEX
          value: "true"
        - name: TESTNET
          value: "true"
        - name: CONNECT_IPS
          value: "35.192.117.201:18000"
        - name: GLOG_V
          value: "0"
        - name: ADMIN_PUBLIC_KEYS
          value: "${admin_public_keys}"
        - name: SUPER_ADMIN_PUBLIC_KEYS
          value: "${admin_public_keys}"
        - name: MINER_PUBLIC_KEYS
          value: "BC1YLg7Bk5sq9iNY17bAwoAYiChLYpmWEi6nY6q5gnA1UQV6xixHjfV"
        - name: NUM_MINING_THREADS
          value: "1"
        - name: BLOCK_PRODUCER_SEED
          value: "essence camp ghost remove document vault ladder swim pupil index apart ring"
        - name: STARTER_DESO_SEED
          value: "road congress client market couple bid risk escape artwork rookie artwork food"
        - name: BLOCK_CYPHER_API_KEY
          value: "092dae962ea44b02809a4c74408b42a1"
        - name: MIN_SATOSHIS_FOR_PROFILE
          value: "0"
        - name: SHOW_PROCESSING_SPINNERS
          value: "true"
        - name: METAMASK_AIRDROP_DESO_NANOS_AMOUNT
          value: "1000"
        - name: DATA_DIR
          value: "/etc/backend-volume"
        - name: SQS_URI
          value: "placeholder"
        - name: GLOBAL_STATE_API_URL
          value: "https://test.deso.org"
        - name: EXPOSE_GLOBAL_STATE
          value: "true"
        - name: RUN_HOT_FEED_ROUTINE
          value: "true"
        - name: HOT_FEED_MEDIA_REQUIRED
          value: "true"
      perEnv: [ ]
    ports:
    - name: http1
      protocol: TCP
      containerPort: 18000
      servicePort: 18000
    - name: http2
      protocol: TCP
      containerPort: 18001
      servicePort: 18001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-external
    # kubernetes.io/tls-acme: "true"
  paths:
    - path: /api
      servicePort: 18001
  hosts:
  %{ if length(service_hosts) > 0 }
    %{ for host in service_hosts }
    - ${host}
    %{ endfor }
  %{ else }
    [ ]
  %{ endif }
  tls: []
