replicaCount: ${replica_count}

fullnameOverride: ${fullnameOverride}
namespace: ${namespace}


deployment:
  containers:
  - name: ${fullnameOverride}
    image:
      repository: ${docker_repository}
      tag: ${docker_tag}
      pullPolicy: Always
    args:
    - run
    env:
      base:
        - name: TXINDEX
          value: "false"
        - name: GLOG_V
          value: "0"
        - name: ADMIN_PUBLIC_KEYS
          value: "BC1YLjUrkSFEW1XyfZ6JdbdVmDURFG3PxJmZ7LKw4zs6PCFLXKeM2YJ BC1YLfrvJwwAjDcL3Tq2spWbvXCJFadiDdJMyvCaeHgG7snSsYNRKXk BC1YLhKuj76oaT1wwGhfb9GX7rCyc9cxrx54v84fAn9EDuc9zDawgGf BC1YLh6WDX4uCw3pcT7pjEQG7UcLj1KS1SpG3hnLkWg11EiBGjAM6oP BC1YLfyqxLpXsiGt7HvgjaKBjCZjAev82HeM626Nw7zfuYowrY72fGP BC1YLhSkJo5dhiFK38eFdViXm1tsAVi1ZFdNroG1RoB8NJG4JnDLzNK BC1YLgC4t51g6NTmd9gMzrdyfVHE94r7HiPWCq3nk1H7E7csDToXEVK BC1YLjVqfEj98Uj2dZcQJfWg9E43qdhp8Zg2CiSZTQshsWzgknLeTEh BC1YLhSkJo5dhiFK38eFdViXm1tsAVi1ZFdNroG1RoB8NJG4JnDLzNK BC1YLitDQpQycqHf8sni9vJgSeYqfH6G2w7UPUzZNUgX3bofqnh5y8x BC1YLhKuj76oaT1wwGhfb9GX7rCyc9cxrx54v84fAn9EDuc9zDawgGf BC1YLibJzKxiMTJubkStWfmmAVP75FjZcNaY7Mwi34cvZSAkq5sWuKY BC1YLgikddZV7MwhXjEoKGt5sNRJTw35Vv4c5BB5xXv7RHUi2C6MY56 BC1YLgFSYXwccnsm68JJgmyfjDJivbree9Kmt43mrPqiM6c1F7Swa5q"
        - name: SUPER_ADMIN_PUBLIC_KEYS
          value: "BC1YLjUrkSFEW1XyfZ6JdbdVmDURFG3PxJmZ7LKw4zs6PCFLXKeM2YJ BC1YLfrvJwwAjDcL3Tq2spWbvXCJFadiDdJMyvCaeHgG7snSsYNRKXk BC1YLhKuj76oaT1wwGhfb9GX7rCyc9cxrx54v84fAn9EDuc9zDawgGf BC1YLh6WDX4uCw3pcT7pjEQG7UcLj1KS1SpG3hnLkWg11EiBGjAM6oP BC1YLfyqxLpXsiGt7HvgjaKBjCZjAev82HeM626Nw7zfuYowrY72fGP BC1YLhSkJo5dhiFK38eFdViXm1tsAVi1ZFdNroG1RoB8NJG4JnDLzNK BC1YLgC4t51g6NTmd9gMzrdyfVHE94r7HiPWCq3nk1H7E7csDToXEVK BC1YLjVqfEj98Uj2dZcQJfWg9E43qdhp8Zg2CiSZTQshsWzgknLeTEh BC1YLhSkJo5dhiFK38eFdViXm1tsAVi1ZFdNroG1RoB8NJG4JnDLzNK BC1YLitDQpQycqHf8sni9vJgSeYqfH6G2w7UPUzZNUgX3bofqnh5y8x BC1YLhKuj76oaT1wwGhfb9GX7rCyc9cxrx54v84fAn9EDuc9zDawgGf BC1YLibJzKxiMTJubkStWfmmAVP75FjZcNaY7Mwi34cvZSAkq5sWuKY BC1YLgikddZV7MwhXjEoKGt5sNRJTw35Vv4c5BB5xXv7RHUi2C6MY56 BC1YLgFSYXwccnsm68JJgmyfjDJivbree9Kmt43mrPqiM6c1F7Swa5q"
        #- name: POSTGRES_URI
        #  value: "postgres://${pg_username}:${pg_password}@${pg_hostname}:${pg_port}/${pg_name}"
        - name: RATE_LIMIT_FEERATE
          value: "0"
        - name: MIN_FEERATE
          value: "1000"
        - name: STARTER_BITCLOUT_NANOS
          value: "1000000"
        - name: MIN_SATOSHIS_FOR_PROFILE
          value: "50000"
        - name: DATA_DIR
          value: "/etc/backend-volume"
        - name: SQS_URI
          value: "${sqs_uri}"
        - name: GLOBAL_STATE_API_URL
          value: "https://node.deso.org"
        - name: RUN_HOT_FEED_ROUTINE
          value: "true"
        - name: HOT_FEED_MEDIA_REQUIRED
          value: "true"
      perEnv: [ ]
    ports:
    - name: http1
      protocol: TCP
      containerPort: 17000
      servicePort: 17000
    - name: http2
      protocol: TCP
      containerPort: 17001
      servicePort: 17001

    resources:
      requests:
        memory: ${requests_memory}
        cpu: ${requests_cpu}


    volumeMounts:
    # name must match the volume name below
    - name: pearl-backend-vol-v2
      mountPath: /etc/backend-volume


volumes:
- name: pearl-backend-vol-v2
  persistentVolumeClaim:
    claimName: pearl-backend-vol-v2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-external
    # kubernetes.io/tls-acme: "true"
  paths:
    - path: /api
      servicePort: 17001
  hosts:
    - api.prod.yourgem.app
    - api.pearl.app
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
