# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Docker hub
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY_NAME: 067550988196.dkr.ecr.us-east-1.amazonaws.com/backend
    steps:
      # Checking out multilple repo side by side
      # https://github.com/actions/checkout#checkout-multiple-repos-private
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: backend

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: TheBitGram/core
          path: core
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_CORE }}


      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docs: https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_REPOSITORY_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  # Deploy to dev
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Extract tag var
      id: tag_id
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Update dev image tag
      uses: jacobtomlinson/gha-find-replace@0.1.4
      with:
        find: "docker_tag        = \"*\""
        replace: "docker_tag        = \"${{ steps.tag_id.outputs.tag }}\""
        include: "terraform-environments/aws/dev/helm/60-gem-backend/"

    # - name: Update dev image tag
    #   run: |
    #     terraform apply -auto-approve
    #     echo ${{ steps.tag_id.outputs.tag }}


    - name: Update dev deploy docker tags
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        file_pattern: terraform-environments/*

